//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_RevisionFirma
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_RevisionFirma.IWSArchivos")]
    public interface IWSArchivos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSArchivos/VerificarFirma", ReplyAction="http://tempuri.org/IWSArchivos/VerificarFirmaResponse")]
        System.Threading.Tasks.Task<string[]> VerificarFirmaAsync(string Ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSArchivos/GenerarAcuse", ReplyAction="http://tempuri.org/IWSArchivos/GenerarAcuseResponse")]
        System.Threading.Tasks.Task<string[]> GenerarAcuseAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWSArchivosChannel : wcf_RevisionFirma.IWSArchivos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WSArchivosClient : System.ServiceModel.ClientBase<wcf_RevisionFirma.IWSArchivos>, wcf_RevisionFirma.IWSArchivos
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSArchivosClient() : 
                base(WSArchivosClient.GetDefaultBinding(), WSArchivosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSArchivos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSArchivosClient(EndpointConfiguration endpointConfiguration) : 
                base(WSArchivosClient.GetBindingForEndpoint(endpointConfiguration), WSArchivosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSArchivosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSArchivosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSArchivosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSArchivosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSArchivosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> VerificarFirmaAsync(string Ruta)
        {
            return base.Channel.VerificarFirmaAsync(Ruta);
        }
        
        public System.Threading.Tasks.Task<string[]> GenerarAcuseAsync(string id)
        {
            return base.Channel.GenerarAcuseAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSArchivos))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSArchivos))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/wcf_RevisionFirma/WSRevisionFirma.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSArchivosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSArchivos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSArchivosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSArchivos);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSArchivos,
        }
    }
}
